### ISSUE TITLE
Syntax Error with Yaml 

### ISSUE THREAD

**Issue by oluwayetty** [mcsix/xela-server-ros#2]
Afte running `roslaunch xela_server service.launch`, I came across this error which I could not fix.
I am using ROS-KINETIC which does not work with python3, only python2. My virtual env python version is 3.5 so I am not sure why this error occurs but my best guess is that it is due to the fact that python2 does not support `metaclass`.

Traceback (most recent call last):
  File "/opt/ros/kinetic/bin/roslaunch", line 34, in <module>
    import roslaunch
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 51, in <module>
    from . import param_dump as roslaunch_param_dump
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/param_dump.py", line 40, in <module>
    import roslaunch.config
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 45, in <module>
    import rospkg.distro
  File "/home/yetty/xela/venv/lib/python3.5/site-packages/rospkg/distro.py", line 44, in <module>
    import yaml
  File "/home/yetty/xela/venv/lib/python3.5/site-packages/yaml/__init__.py", line 284
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax

**Comment by mcsix** [comment]
It seems to be common issue with ROS Kinetic.
Whilst I am not 100% sure which method would work the best for you, I recon that [this](https://answers.ros.org/question/47018/rosinstall-on-ubuntu-1104/) might help. It includes same problem on earlier ROS, the guide might be in the last post though.
